### ISSUE TITLE
${java.home} not set correctly in builds that use STF based systemtests 

### ISSUE THREAD

**Issue by Mesbah-Alam** [AdoptOpenJDK/stf#18]
After incorporating the systemtest with openjdk-test, we are seeing an issue where java8_bindir variable doesn't point to the correct path. 

The issue occurs in builds triggered from upstream, e.g.:
https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_openj9_test_x86-64_linux/91/consoleFull

However, the issue does not occur when we launch the same build manually, using 'nightly' sdk, e.g.: https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_openj9_test_x86-64_linux/90/consoleFull

**Comment by Mesbah-Alam** [comment]
${java8_bindir} is set based on ${java8_home} (in stf.build/include/top.xml), and ${java8_home} is set based ${java.home} (in openjdk.build/include/top.xml, target `setup-java8-properties). 

In the failing case, we need to find out what ${java.home} is being set to.

**Comment by Mesbah-Alam** [comment]
Temporarily disabled systemtests to be built as part of openjdk-test builds : https://github.com/AdoptOpenJDK/openjdk-tests/pull/189

**Comment by Mesbah-Alam** [comment]
Hi Simon, 

We could not solve the issue why java8_bindir doesn't get set every now and again. 

It sometimes works, e.g. it worked here : https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_openj9_test_x86-64_linux/93/consoleFull

On the same machine, it failed here: https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_openj9_test_x86-64_linux/94/console

Please note that, I have added the debug line to print java.home in "setup-java8-properties" target in openjdk.build/include/top.xml. 

So, in the job where it fails (https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk9_openj9_test_x86-64_linux/94/consoleFull), it prints out this: 

`21:09:24 setup-java8-properties:
21:09:24      [echo] java.home is /usr/lib/jvm/java-9-openjdk-amd64
21:09:24      [echo] java8_bindir set to ${java8_bindir}
21:09:24      [echo] java8_compiler set to /home/jenkins/workspace/openjdk9_openj9_test_x86-64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build/${java8_bindir}/javac`

So, what I notice is: 
1) Even when java.home has a value, java8_bindir is not evaluating to a value. 
2) It looks like java.home is pointing to a default installation location of Java, not the SDK that is downloaded under workspace (e.g., as Stewart saw in one of the failing machines, sdk is being downloaded to "/home/jenkins/workspace/openjdk9_openj9_test_x86-64_linux/openjdkbinary/j2sdk-image"). 

Does this mean that the systemtest build system absolutely requires that JAVA_HOME be set prior to running the scripts? 

testKitGen avoids setting JAVA_HOME, but instead defines JAVA_DIR which is the same as JAVA_HOME. 

@lumpfish

**Comment by lumpfish** [comment]
It is not the stf repository build which is failing, it is the openjdk-systemtest repository build (stf.build/include/top.xml does not contain the set-platform-properties macro, it is only in openjdk-systemtest.build/include/top.xml).

In a failing run I see

21:09:24 setup-java8-properties:
21:09:24      [echo] java.home is /usr/lib/jvm/java-9-openjdk-amd64
21:09:24      [echo] java8_bindir set to ${java8_bindir}
21:09:24      [echo] java8_compiler set to /home/jenkins/workspace/openjdk9_openj9_test_x86-64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build/${java8_bindir}/javac
21:09:24      [echo] Running ${java8_bindir}/java -XshowSettings:properties -version to determine java platform

In a passing run I see

20:43:27 setup-java8-properties:
20:43:27      [echo] java.home is /usr/lib/jvm/java-9-openjdk-amd64
20:43:27      [echo] java8_bindir set to /usr/lib/jvm/java-9-openjdk-amd64/bin
20:43:27      [echo] java8_compiler set to /usr/lib/jvm/java-9-openjdk-amd64/bin/javac
20:43:27      [echo] Running /usr/lib/jvm/java-9-openjdk-amd64/bin/java -XshowSettings:properties -version to determine java 

Note the difference for the java8_compiler setting:

Failing:
java8_compiler set to /home/jenkins/workspace/openjdk9_openj9_test_x86-64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build/${java8_bindir}/javac

Passing:
java8_compiler set to /usr/lib/jvm/java-9-openjdk-amd64/bin/javac

The code for assigning java8_compiler says:
			property name="@{java.compiler.property}" location="${@{java.bindir.property}}/javac${exe_suffix}"

Which when the @ variables are resolved says:
			property name="java8_compiler" location="${java8_bindir}/javac${exe_suffix}"

Since we know that java8_bindir has no value (it prints as ${java8_bindir}), this assignment is not happening, which means that java8_compiler must already have a value at this point (ant properties are immutable).

How exactly are the stf and openjdk-systemtest repository builds being invoked by testkitgen?  Are ant tasks being used (the ant task doc says "By default, all of the properties of the current project will be available in the new project. Alternatively, you can set the inheritAll attribute to false and only "user" properties (i.e., those passed on the command-line) will be passed to the new project. In either case, the set of properties passed to the new project will override the properties that are set in the new project")?  My hunch is that java8_compiler is being set in an ant task prior to the failing job which overrides the setting in the build because properties are immutable.

Also what is the difference between the failing and passing runs in terms of exactly which java version is being used for the different parts of the setup and build process?

**Comment by lumpfish** [comment]
The value of java8_compiler appearing as
java8_compiler set to /home/jenkins/workspace/openjdk9_openj9_test_x86-64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build/${java8_bindir}/javac
can be explained by ant's behaviour when a file cannot be located:

From the ant property task documentation:
"location:  Sets the property to the absolute filename of the given file. If the value of this attribute is an absolute path, it is left unchanged (with / and \ characters converted to the current platforms conventions). Otherwise it is taken as a path relative to the project's basedir and expanded."

So that would explain how "/home/jenkins/workspace/openjdk9_openj9_test_x86-64_linux/openjdk-test/systemtest/openjdk-systemtest/openjdk.build" is added to the front of the code.

So the issue is still why does the available task think that neither ${java.home}/bin/javac nor ${java.home}/jre/bin exists.

Are the passing and failing tests running on the same machine?

**Comment by lumpfish** [comment]
Is it possible that the ant java.home property (i.e. the java system property) has trailing whitespace in the failing jobs, which means we would be looking for ${java.home}/jre(space)/bin/javac, not ${java.home}/jre/bin/javac?

**Comment by lumpfish** [comment]
Got some help from @sxa looking at the java installations in the different runs.  There is no trailing space in the java.home property, but the java installed at /usr/lib/jvm/java-9-openjdk-amd64/bin has no javac in it (a jre rather than a jdk installation).  One the machine where the test passes there is a javac.
So the code is working as designed.  The java being used for the test material build is expected to be a full jdk.

**Comment by sxa** [comment]
We'll need to look into the ansible scripts to determine exactly why but here's the output from `test-scaleway-x64-ubuntu-16.04-1`:

```
$ dpkg -S /usr/lib/jvm/java-9-openjdk-amd64/bin/java
openjdk-9-jre-headless:amd64: /usr/lib/jvm/java-9-openjdk-amd64/bin/java
```

and here's the same from `test-packet-x64-ubuntu-16.04-1`:

```
jenkins@test-packet-x64-ubuntu-16:~$ dpkg -S /usr/lib/jvm/java-9-openjdk-amd64/bin/java
openjdk-9-jre-headless:amd64: /usr/lib/jvm/java-9-openjdk-amd64/bin/java
```

**Comment by Mesbah-Alam** [comment]
> How exactly are the stf and openjdk-systemtest repository builds being invoked by testkitgen? Are ant tasks being used

Yes, Ant is being used to clone and build stf and openjdk-systemtest materials. 

`<target name="build-dependencies" depends="compile_stf">
		<ant antfile="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build/build.xml" dir="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build" inheritAll="false"/>
		<antcall target="dist" inheritall="true" />
	</target>`

`<target name="compile_stf" depends="configure_stf">
		<ant antfile="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build/build.xml" dir="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build/" inheritAll="false" />
	</target>`

`<target name="configure_stf" depends="check_systemtest">
		<ant antfile="${SYSTEMTEST_ROOT}/stf/stf.build/build.xml" dir="${SYSTEMTEST_ROOT}/stf/stf.build/" target="configure" inheritAll="false" />
		<ant antfile="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build/build.xml" dir="${SYSTEMTEST_ROOT}/openjdk-systemtest/openjdk.build/" target="configure" inheritAll="false" />
	</target>`

inheritall="true" in "build-dependencies" target may need to be set to "false".

**Comment by Mesbah-Alam** [comment]
As discussed with Simon and Shelley, setting JAVA_HOME to the SDK under test in the Jenkinsfile solves the problem, as STF requires JAVA_HOME to be set in order for it to figure out which JDK to use for compiling STF and systemtest artifacts. 

I made the update to Jenkinsfile in my branch and ran ran a few builds to test: 

1) Here's a `openjdk9_openj9_systemtest_x64_linux` build I launched manually with "nightly" SDK : https://ci.adoptopenjdk.net/view/work%20in%20progress/job/openjdk9_openj9_systemtest_x64_linux/33/consoleFull

2) Here's a `openjdk9_openj9_test_x86-64_linux` build launched with upstream SDK: https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/Mesbah_openjdk9_openj9_test_x86-64_linux/1/console

In both the cases, java.home , java8_bindir, and java8_compiler are now pointing to the SDK under test.

**Comment by Mesbah-Alam** [comment]
New PR created with the changes: https://github.com/AdoptOpenJDK/openjdk-tests/pull/191
